### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by jorgeaaq70** [FlexConfirmMail/Outlook#21]
I create the ADMX files for es-ES with spanish translation but I can not get that FlexConfirmMail use them 

I need to do anything else? 

Attached are the spanish translated version ... (change the extension for upload) 

[FlexConfirmMailDefault.adml.txt](https://github.com/FlexConfirmMail/Outlook/files/15084000/FlexConfirmMailDefault.adml.txt)
[FlexConfirmMail.adml.txt](https://github.com/FlexConfirmMail/Outlook/files/15084001/FlexConfirmMail.adml.txt)

I put the files in  \\domain.com\SYSVOL\csags.com.mx\Policies\PolicyDefinitions

English version work , but I cannot get the spanish version to work

**Comment by HashidaTKS** [comment]
> I put the files in \domain.com\SYSVOL\csags.com.mx\Policies\PolicyDefinitions

Please let me check, did you put those translated adml files to ` \domain.com\SYSVOL\csags.com.mx\Policies\PolicyDefinitions\es-ES` and admx files to ` \domain.com\SYSVOL\csags.com.mx\Policies\PolicyDefinitions` ?

> Attached are the spanish translated version ... (change the extension for upload)

It seems that following settings are incorrect.

FlexConfirmMailDefault.adml
``` adml
    <presentationTable>
      <presentation id="CountSeconds">
        <decimalTextBox refId="ContarSegundos" defaultValue="3" spinStep="1">Segundos</decimalTextBox>
      </presentation>
      <presentation id="SafeBccThreshold">
        <decimalTextBox refId="UmbralBccSeguros" defaultValue="4" spinStep="1">Numero de Dominios</decimalTextBox>
      </presentation>
      <presentation id="TrustedDomains">
        <multiTextBox refId="DominiosSeguros"/>
      </presentation>
      <presentation id="UnsafeDomains">
        <multiTextBox refId="DominiosInseguros"/>
      </presentation>
      <presentation id="UnsafeFiles">
        <multiTextBox refId="ArchivosInseguros"/>
      </presentation>
    </presentationTable>
```

You should specify a correspondinf id in the admx file as `refid`s.

``` adml
    <presentationTable>
      <presentation id="CountSeconds">
        <decimalTextBox refId="CountSeconds" defaultValue="3" spinStep="1">Segundos</decimalTextBox>
      </presentation>
      <presentation id="SafeBccThreshold">
        <decimalTextBox refId="SafeBccThreshold" defaultValue="4" spinStep="1">Numero de Dominios</decimalTextBox>
      </presentation>
      <presentation id="TrustedDomains">
        <multiTextBox refId="TrustedDomains"/>
      </presentation>
      <presentation id="UnsafeDomains">
        <multiTextBox refId="UnsafeDomains"/>
      </presentation>
      <presentation id="UnsafeFiles">
        <multiTextBox refId="UnsafeFiles"/>
      </presentation>
    </presentationTable>
```

Also, please note that FlexConfirmMail's UI does not support Spanish, even if these adml files work correctly.

**Comment by HashidaTKS** [comment]
> Also, please note that FlexConfirmMail's UI does not support Spanish, even if these adml files work correctly.

We also welcome a PR for translating the UI resource files for Spanish :)

https://github.com/FlexConfirmMail/Outlook/tree/master/Properties

**Comment by jorgeaaq70** [comment]
I am going to change the files and probe 

but, I do my FIRST contribution to a project on Github with the files Resources.es.resx with the Translation for the UI to spanish!! and the translated files for policy es-ES

**Comment by jorgeaaq70** [comment]
Hi, I do not have the tools to create the executable, can someone help me compiling and publishing the exec with the new language please!

thanks in advance

**Comment by HashidaTKS** [comment]
Close because we now release v22.7 that includes this change.

https://github.com/FlexConfirmMail/Outlook/releases/tag/v22.7
